### ISSUE TITLE
README example not working

### ISSUE THREAD

**Issue by zcei** [derhuerst/vbb-find-stations#4]
Hej fellow Berliner,

just wanted to give your `vbb-*` modules a try (to get IDs for your [station photo module](https://github.com/derhuerst/vbb-station-photos)) and the README is lacking any documentation about `fuzzy` & `exact` which I found in the code.

Is the module intended to be only used with those filter methods? 
What about using `exact` as default filter, so it doesn't crash?

`npm@4.0.5`
`node@7.7.0`

**Comment by zcei** [comment]
Also might be good to reflect deprecation of `vbb-static`, as code is already using `vbb-stations`

**Comment by derhuerst** [comment]
Hey @zcei, thanks for giving this module a try!

> Is the module intended to be only used with those filter methods?

No, that's why you're able to pass a custom function into `findStations`. I should probably document that.

> What about using exact as default filter, so it doesn't crash?

I'm fine with that. Will change it.
