### ISSUE TITLE
Make station properties available

### ISSUE THREAD

**Issue by zcei** [derhuerst/vbb-find-stations#5]
As `for-in` loops without guarding for own properties is an anti-pattern, plus it renders `Object.keys`, `console.dir` (and alike stuff) useless, I propose changing [those two lines](https://github.com/derhuerst/vbb-find-stations/blob/master/index.js#L46-L48).

```diff
- station = Object.create(station)
- station.relevance = relevance
+ station = Object.assign({}, station, { relevance })
```

(For immutability reasons you might want to choose a distinct name like `stationWithRelevance`)

**Comment by derhuerst** [comment]
> As `for-in` loops without guarding for own properties is an anti-pattern

Where do you see a `for … in` loop, except in the build script?

About the `Object.keys` thing: I'm not sure I'm following you here? Is it that `console.log`ging a result is counter-intuitive because I use `Object.create`?

**Comment by zcei** [comment]
As a normal dev I'd expect to see relevant parts of my object within the object itself (so called "own" properties):

```js
// assuming `s` is a station object

console.dir(s)
// { relevance: 1.0217391304347827 }

Object.keys(s)
// [ 'relevance' ]
```

What I currently need to do, is to check the prototype chain of the station, which is questionable from a design standpoint (your prototype includes station specific information), and at least is uncomfortable to work with.

```js
Object.getPrototypeOf(station)
// { id: '900000009202',
//   name: 'U Osloer Str. (Berlin)',
//   tokens: [ 'ubahn', 'osloer', 'strasse', 'berlin' ] }


for (key in s) {
  console.log(`${key}: ${s[key]}`)
}
// relevance: 1.0227272727272727
// id: 900000009202
// name: U Osloer Str. (Berlin)
// tokens: ubahn,osloer,strasse,berlin
```

What you're doing in the first line is creating a new object and explicitly setting the passed in `station` as its prototype. A possible second parameter would describe additional own properties of the object you're about to create:

```js
const props = Object.keys(station).reduce((props, key) => {
  props[key] = { value: station[key], enumerable: true }
  return props
}, {})
Object.create(null, props)
// { id: '900000009272',
//   name: 'U Osloer  Str. (Berlin)',
//   tokens: [ 'ubahn', 'osloer', 'strasse', 'berlin' ],
//   relevance: 1.0217391304347827 }
```

Which in my humble opinion is super ugly, and is actually what `Object.assign` does for us.
I assume the `Object.create` was intended for cloning, therefore the empty object at the beginning, and you're copying over all the attributes.
(Please note, that the `token` array will in either case be copied by reference)

**Comment by derhuerst** [comment]
I know what `Object.create` does. The reason I use it in this case is efficiency, but I guess it's rather a case of premature optimisation. From a design standpoint, what's wrong with using the prototype for readonly data? From a UX perspective, I totally agree, it's hard to find even for experienced devs.

**Comment by zcei** [comment]
I tend to understand prototypical inheritance as a composition of functionality for related (kinda duck-typed) entities. For example `isPrototypeOf` checks.
Or for example one could create a `neighbourStations` function, that checks on the stations id and returns the stations next to it. That functionality would be independent from the actual values of `id`, `name`, etc.
(Also the efficiency is questionable as you implicitly walk up the prototype chain, but that's so micro-scale though.. neglect-able)

If you really want to have the values read-only, why not use `defineProperty` (or `Object.create` with the second parameter) and set `writable: false`? 
Or make use of ES2015 Proxies, if you really care about how your data is accessed.

**Comment by derhuerst** [comment]
@zcei I like to use the prototype system for adding contextual information (like search relevance) to a more general object. i don't use prototypal *inheritance* often (or inheritance at all) and in this case my use of `Object.create` is not about inheritance. It's such a shame only a few JS devs know about the simplicity of the prototype system, so that it's basically non-idiomatic to use it.

> (Also the efficiency is questionable as you implicitly walk up the prototype chain, but that's so micro-scale though.. neglect-able)

fair point. my point was mostly about allocations. it is a mental leftover from other/former VBB build scripts in which garbage collection really became the bottleneck.

> If you really want to have the values read-only, why not use `defineProperty` […]?

this wasn't about read-only entries.

> Or make use of ES2015 Proxies, if you really care about how your data is accessed.

using a language feature that is not widely supported and can't be nicely shimmed is a no-go for me, especially if there's no *real* (as in significantly simplifying) use case for it.

with many choices, i tend to stick closer to the [non-fancy style](https://github.com/yoshuawuyts/tiny-guide-to-non-fancy-node/blob/master/README.md#tiny-guide-to-non-fancy-node).

----

Moving on with this, I will change it to use `Object.assign`, as i cannot defend my subjective guesses about the performance of this code against the argument of usability with `console.log`/`Object.keys`.

**Comment by zcei** [comment]
> in this case my use of Object.create is not about inheritance. It's such a shame only a few JS devs know about the simplicity of the prototype system, so that it's basically non-idiomatic to use it.

That's why I said that *I tend* for myself to use it like this - always inspiring to see how other people make use of it. That's what the whole discussion is about for me 🙂 

> this wasn't about read-only entries.

Then I miss-understood your former question about what would be wrong with using the prototype for readonly data - sorry!

As it wasn't about making it read-only the Proxies are from the table (but in general I make use of features that are in the latest LTS, if they solve my problem in a readable way) - the intention was to offer multiple solutions to choose from instead of just ranting about your (actually awesome) commitment to the public transport data.

Nice to hear that you agree with me on the last point (or at least "can't defend").

**Comment by derhuerst** [comment]
btw: have you been to the [oklab berlin](http://codefor.de/berlin/) before?

**Comment by zcei** [comment]
Nope, sadly heard about it for the first time, even though I used to work close by.
Are you attending regularly? Would be interested to hear about what you're working on, so I'll try to join for a Vorstellungsrunde on 13th of March (as Saturdays are booked by another pet-project 😇)

**Comment by derhuerst** [comment]
> Are you attending regularly?

Yep, almost every week.

> […] I'll try to join for a Vorstellungsrunde on 13th of March

Nice, let me know!

**Comment by derhuerst** [comment]
Fixed as of 2cbcc1041ccc2e012cda9c37c8e0e21466747586.

**Comment by derhuerst** [comment]
@zcei

> […] I'll try to join for a Vorstellungsrunde on 13th of March

I'll have to cancel this, sorry. Forgot to let you know earlier.

**Comment by zcei** [comment]
Oh that's sad, was just about to reach out to you via Twitter.
Loosens my plans for the week a bit, though 👍

**Comment by derhuerst** [comment]
If you're interested in open data & civic tech in general, it's still worthwhile to attend the "Vorstellungsrunde" at the OKLab tonight. I'll hopefully be there next time. Usually, I attend every week, but I'm not in Berlin right now.

@juliuste and @tursics also often attend this and might help you with more transport-related information.

**Comment by tursics** [comment]
Oh. Today I will not attend the weekly meeting @derhuerst and @zcei. I hope @juliuste will be there tonight.

**Comment by zcei** [comment]
Haha okay, sounds like today is not the best fit to start - kinda welcome for this week, I guess I'll just join next week without the official "Vorstellungsrunde", as I already stalk you guys here on GitHub 😉

**Comment by juliuste** [comment]
I won't be there next week, but hopefully either @derhuerst or @tursics (probably both of them) can make it 👍

**Comment by zcei** [comment]
Ah damnit, totally forgot about it 😞 👎 
Another week, another try haha
